/*
	Copyright 2023 48Club

	This file is part of the puissant-bsc-validator library and is intended for the implementation of puissant services.
	Parts of the code in this file are derived from the go-ethereum library.
	No one is authorized to copy, modify, or publish this file in any form without permission from 48Club.
	Any unauthorized use of this file constitutes an infringement of copyright.
*/

package miner

import (
	"context"
	"errors"
	"fmt"
	"github.com/ethereum/go-ethereum/common"
	lru2 "github.com/ethereum/go-ethereum/common/lru"
	"github.com/ethereum/go-ethereum/consensus"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/core/txpool"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/log"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
	"math"
	"math/big"
	"time"
)

// generateParams wraps various of settings for generating sealing task.
type generateParams struct {
	timestamp   uint64            // The timestamp for sealing task
	forceTime   bool              // Flag whether the given timestamp is immutable or not
	parentHash  common.Hash       // Parent block hash, empty means the latest chain head
	coinbase    common.Address    // The fee recipient address for including transaction
	random      common.Hash       // The randomness generated by beacon chain, empty before the merge
	withdrawals types.Withdrawals // List of withdrawals to include in block.
	noTxs       bool              // Flag whether an empty block without any transaction is expected
}

type multiPackingWork struct {
	round  int
	income *big.Int
	work   *core.MinerEnvironment
	err    error
}

// makeEnv creates a new environment for the sealing block.
func (w *worker) makeEnv(parent *types.Header, header *types.Header, coinbase common.Address) (*core.MinerEnvironment, error) {
	topState, err := w.chain.StateAt(parent.Root)
	if err != nil {
		return nil, err
	}

	// Note the passed coinbase may be different with header.Coinbase.
	env := &core.MinerEnvironment{
		Signer:   types.MakeSigner(w.chainConfig, header.Number, header.Time),
		GasPool:  core.CreateGasPool(nil, w.chain.Config(), header),
		State:    topState,
		Coinbase: coinbase,
		Header:   header,
	}
	// Keep track of transactions which return errors so they can be removed
	env.TxCount = 0
	return env, nil
}

// commitWork generates several new sealing tasks based on the parent block
// and submit them to the sealer.
func (w *worker) commitWork(interruptCh chan int32, timestamp int64) {
	// Abort committing if node is still syncing
	if w.syncing.Load() {
		return
	}
	start := time.Now()

	// Set the coinbase if the worker is running or it's required
	var (
		coinbase common.Address
		workList = make([]*multiPackingWork, 0, 20)
		//pReporter   = core.NewPuissantReporter()
		//blockNumber uint64
	)
	if w.isRunning() {
		coinbase = w.etherbase()
		if coinbase == (common.Address{}) {
			log.Error("Refusing to mine without etherbase")
			return
		}
	}

	// validator can try several times to get the most profitable block,
	// as long as the timestamp is not reached.
LOOP:
	for round := 0; round < math.MaxInt64; round++ {
		roundStart := time.Now()

		work, err := w.prepareWork(&generateParams{
			timestamp: uint64(timestamp),
			coinbase:  coinbase,
		})
		if err != nil {
			return
		}
		thisRound := &multiPackingWork{round: round, work: work, income: new(big.Int)}
		workList = append(workList, thisRound)

		timeLeft := blockMiningTimeLeft(work.Header.Time)
		if timeLeft <= 0 {
			log.Warn(" 📦 ⚠️ not enough time for this round, jump out",
				"round", round,
				"income", types.WeiToEther(thisRound.income),
				"elapsed", common.PrettyDuration(time.Since(roundStart)),
				"timeLeft", timeLeft,
			)
			break
		}

		// empty block at first round
		if round == 0 {
			//blockNumber = work.Header.Number.Uint64()
			log.Info(" 📦 packing", "round", round, "elapsed", common.PrettyDuration(time.Since(roundStart)))
			continue
		}

		var (
			pendingTxs      map[common.Address][]*txpool.LazyTransaction
			pendingPuissant types.PuissantBundles
		)
		if work.Header.Difficulty.Cmp(diffInTurn) == 0 {
			pendingTxs, pendingPuissant = w.eth.TxPool().PendingTxsAndPuissant(false, work.Header.Time)
		} else {
			pendingTxs = w.eth.TxPool().Pending(false)
		}

		var pendings = make(map[common.Address][]*types.Transaction)
		for from, txs := range pendingTxs {
			for _, tx := range txs {
				pendings[from] = append(pendings[from], tx.Tx.Tx)
			}
		}

		report, err := core.RunPuissantCommitter(
			timeLeft,
			work,
			pendings,
			pendingPuissant,
			w.chain,
			w.chainConfig,
			w.eth.TxPool().DeletePuissantBundles,

			lru2.NewCache[common.Hash, struct{}](1000),
		)
		//pReporter.Update(report, round)
		thisRound.err = err
		thisRound.income = work.State.GetBalance(consensus.SystemAddress)

		roundElapsed := time.Since(roundStart)
		select {
		case signal, ok := <-interruptCh:
			if !ok {
				// should never be here, since interruptCh should not be read before
				log.Warn("commit transactions stopped unknown")
				return
			}
			if err := signalToErr(signal); errors.Is(err, errBlockInterruptedByNewHead) {
				log.Debug("commitWork abort", "err", err)
				return
			} else if errors.Is(err, errBlockInterruptedByTimeout) || errors.Is(err, errBlockInterruptedByOutOfGas) {
				// break the loop to get the best work
				log.Debug("commitWork finish", "reason", err)
				break LOOP
			}
		default:
		}

		roundInterval := repackingInterval(roundElapsed, work.Header.Time)

		log.Info(" 📦 packing",
			"round", round,
			"txs", work.PackedTxs.Len(),
			"triedPuissant", len(report),
			"income", types.WeiToEther(thisRound.income),
			"elapsed", common.PrettyDuration(roundElapsed),
			"timeLeft", blockMiningTimeLeft(work.Header.Time),
			"interval", common.PrettyDuration(roundInterval),
			"err", thisRound.err,
		)

		//break LOOP // TODO testnet

		if roundInterval > 0 {
			ctx, cancel := context.WithTimeout(context.Background(), roundInterval)
			go func() {
				for {
					select {
					case <-ctx.Done():
						return
					case <-interruptCh:
						cancel()
					}
				}
			}()
			<-ctx.Done()
			if errors.Is(ctx.Err(), context.Canceled) {
				log.Info(" ⚠️ jump out due to interruption")
				return
			}
		} else {
			// no time for another round, commit now
			break LOOP
		}
	}
	// get the most profitable work
	bestWork := pickTheMostProfitableWork(workList)
	_ = w.commit(bestWork.work, w.fullTaskHook, true, start)

	//if p, ok := w.engine.(*parlia.Parlia); ok {
	//	go pReporter.Done(bestWork.round, blockNumber, bestWork.income, w.sendMessage, p.MakeTextSigner())
	//}
}

func pickTheMostProfitableWork(workList []*multiPackingWork) *multiPackingWork {
	var (
		bestWork   = workList[0]
		bestReward = workList[0].income
	)

	for _, eachWork := range workList {
		if eachWork.err == nil && eachWork.income.Cmp(bestReward) > 0 {
			bestWork, bestReward = eachWork, eachWork.income
		}
	}

	log.Info("pick the most profitable work", "bestRound", bestWork.round, "bestReward", bestReward)
	return bestWork
}

func repackingInterval(fillElapsed time.Duration, headerTime uint64) time.Duration {
	left := blockMiningTimeLeft(headerTime)
	if left <= fillElapsed {
		return 0
	}
	f := int64(left) / int64(fillElapsed)
	if f > 20 && left > 1000*time.Millisecond+fillElapsed {
		return 500 * time.Millisecond
	} else if f > 10 && left > 500*time.Millisecond+fillElapsed {
		return 200 * time.Millisecond
	} else if f > 5 && left > 300*time.Millisecond+fillElapsed {
		return 100 * time.Millisecond
	} else if f > 1 && left > 20*time.Millisecond+fillElapsed {
		return 20 * time.Millisecond
	}
	return 0
}

func blockMiningTimeLeft(headerTime uint64) time.Duration {
	return time.Until(time.Unix(int64(headerTime), 0))
}

func (w *worker) sendMessage(text string, mute bool) {
	if w.messengerBot == nil {
		return
	}

	var msg = fmt.Sprintf("*%s:* %s\n\n_%s_", w.nodeAlias, text, time.Now().Format(time.DateTime))
	msgBody := tgbotapi.NewMessage(w.messengerGroupID, msg)
	msgBody.ParseMode = "markdown"
	msgBody.DisableWebPagePreview = true
	msgBody.DisableNotification = mute

	if _, err := w.messengerBot.Send(msgBody); err != nil {
		log.Error("message sending failed", "err", err)
	}
}
